### ISSUE TITLE
When metatask is hung, the organization does not load

### ISSUE THREAD

**Issue by VictorMendezGonzalez** [Pedro-vk/EthKudos#103]
It seems that if metatask is hung and cannot load, the system cannot load information of an organization so it cannot show all the information.

**Comment by Pedro-vk** [comment]
The problem seems that is on the router guard that ensures that the status of the connection between the app and the Web3 provider is ok. If MetaMask is hung, the Web3 API is not able to return some basic information that allows detecting the status.

The guard is here: https://github.com/Pedro-vk/EthKudos/blob/master/src/app/shared/guards/is-connected.guard.ts#L17-L28
The solution may be a new connection status like `timeout` and use set it after some seconds without Web3 promises resolutions.
The status detection is here: https://github.com/Pedro-vk/EthKudos/blob/master/src/app/shared/web3.service.ts#L88-L104

**Comment by VictorMendezGonzalez** [comment]
Thanks for this fast resolution!
