### ISSUE TITLE
Can we have some kind of organizational heirarchies in the system.

### ISSUE THREAD

**Issue by stablexbt** [Pedro-vk/EthKudos#43]
Like we can have multiple members, the owner of the organization would be the CEO types.
Then there should be a account type for manager which will have their teams and polls within the team.
Adding more levels to these polls will make it more practically useful

**Comment by Pedro-vk** [comment]
In general, EthKudos solves the simplest use case, that is a group/team/company.
Are you suggesting is grouping some organizations into the same "company", right?
In your idea, the current organization is kept like it is right now?

**Comment by stablexbt** [comment]
Yes, the basic structure is like having multiple organizations for a single company with team managers as admin to their teams organization and CEO is like an admin over all these managers and their teams.

We can introduce an additional admin role for ceo/cto guy within the contract, such that both manager(who is the contract owner of the organization) and the CEO both can have rights to the organization. This way we can get more closer to actual use cases and small companies with more than 1 teams can start adopting ethkudos in their systems.

**Comment by Pedro-vk** [comment]
I suppose that it could make sense depending on the company size. From my point of view, the companies where I was had the use case that covers EthKudos. From my point of view is not necessary to separate by teams, because a company is like a graph, sometimes the people between teams/offices can help between them.
And well, I think that the UX is going to be a little bit messy or confusing. And more complexity on the Smart Contracts.

**Comment by stablexbt** [comment]
I like this dapp a lot and maybe you are right about keep things simple and sleek for the contract. Let's keep it simple and avoid making it a messy database.
